server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://orchestrator:8000/;
  }

  location /media/ {
    proxy_pass http://media-worker:9000/files/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
