server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  client_max_body_size 500m;

  location /api/ {
    proxy_pass http://orchestrator:8000/;
    proxy_read_timeout 1800s;
  }

  location /assets/ {
    proxy_pass http://orchestrator:8000/assets/;
  }

  location /media/ {
    proxy_pass http://media-worker:9000/files/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
